### ISSUE TITLE
Lenovo Yoga 13 Type 20175

### ISSUE THREAD

**Issue by 06chaynes** [alesguzik/linux_detect_tablet_mode#11]
I've been trying to determine how to detect the flip of the screen for tablet mode, but so far haven't been able to find the input device tied to the event. I checked each entry in /dev/input/by-path but it doesn't appear to be there. Wondering if you have any experience with this model?

Lenovo Yoga 13 Type 20175
Manjaro 18.1.0 (5.2.20-1-MANJARO)

**Comment by alesguzik** [comment]
Do you mean to detect a change from laptop to tablet mode, or to detect screen orientation in tablet mode?

**Comment by alesguzik** [comment]
To detect a change from laptop to tablet mode run `stdbuf -oL libinput debug-events|grep switch` and flip it between normal/tablet. For screen orientation detection you may use accelerometers. They are available either via DBus using iio-sensor-proxy or directly via `/sys/bus/iio/devices/iio:device*`. You may see the code for working with accelerometers in the older version of this repo: https://github.com/alesguzik/linux_detect_tablet_mode/tree/c5f08f330ef7ab1ccbdaec0697acd780f4f74787
