### ISSUE TITLE
Manjaro 19.0 error

### ISSUE THREAD

**Issue by terrigan** [alesguzik/linux_detect_tablet_mode#12]
I have an Asus Q551LN running Manjaro 19. Installed ruby and other deps for your script and configured. Did not run when restarting WM or reboot. Ran manually for this error:

Traceback (most recent call last):
	7: from /usr/bin/watch_tablet:40:in `<main>'
	6: from /usr/bin/watch_tablet:26:in `run_watcher'
	5: from /usr/bin/watch_tablet:14:in `config'
	4: from /usr/bin/watch_tablet:7:in `load_config!'
	3: from /usr/lib/ruby/2.7.0/psych.rb:277:in `load'
	2: from /usr/lib/ruby/2.7.0/psych.rb:390:in `parse'
	1: from /usr/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
/usr/lib/ruby/2.7.0/psych.rb:456:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 3 column 3 (Psych::SyntaxError)

**Comment by alesguzik** [comment]
What is the content of your `~/.config/watch_tablet.yml`?
