### ISSUE TITLE
Doesn't work for me since stdbuf -oL libinput debug-events|grep switch needs to be run as root

### ISSUE THREAD

**Issue by coldspark29** [alesguzik/linux_detect_tablet_mode#22]
The title describes everything. I can't run it from ``~/.xinitrc`` because I need root privilges. How does this work for you?

**Comment by alesguzik** [comment]
Your user must be in the `input` group (or an equivalent for your distribution) to be able to use it without root privileges. You may see the group name via `ls -l /dev/input/`. To see a list of your groups run `groups`. To add your user to the `input` group you might use `sudo gpasswd --add yourusername input`. Group membership is applied at login, so you might need to restart your X11 session or restart your computer.

**Comment by alesguzik** [comment]
I've updated the readme to include information about `input` group membership.
