### ISSUE TITLE
x1 yoga 3rd gen

### ISSUE THREAD

**Issue by lsmith77** [alesguzik/linux_detect_tablet_mode#5]
running your script I get:

```
$ ./linux_detect_tablet_mode/watch_tablet 
This set of scripts requires 2 accelerometers to detect angle between
a keyboard and a display. Your system has 1, sorry.
```

Based on the below output I would expect there to be 2 devices

```
[lsmith@manjaro ~]$ ls /sys/bus/iio/devices/iio\:device
iio:device0/ iio:device1/ iio:device2/ 
```

however my Ruby foo is insufficient to really understand the parsing you do there and how to fix it ..

**Comment by alesguzik** [comment]
In each of those iio:device* folders should be a file with a name "name", which should contain device type. On my system a command `cat /sys/bus/iio/devices/iio:device*/name` returns
```
      2 accel_3d
      1 als
      1 dev_rotation
      1 geomagnetic_orientation
      1 gyro_3d
      1 incli_3d
      1 magn_3d
```
In your case it's likely that you don't have 2 accel_3d iio devices

**Comment by lsmith77** [comment]
I am getting

```
$ cat /sys/bus/iio/devices/iio:device*/name
gyro_3d
accel_3d
als
```

So the question is then, did Lenovo reduce the capabilities in the 3rd gen or do I maybe need to enable them somehow?

I do have `iio-sensor-proxy` installed. I am running Manjaro.

**Comment by alesguzik** [comment]
Most likely this particular functionality is just implemented differently on gen3 - as far as I remember some other Lenovo Yoga laptops had an acpi event for tablet-laptop transition. As for having less sensors than gen2 - maybe some of them are newer and so are not recognized by the kernel.

**Comment by lsmith77** [comment]
ok thx.
