### ISSUE TITLE
libinput error with touchpad

### ISSUE THREAD

**Issue by Tuxman2** [alesguzik/linux_detect_tablet_mode#9]
Hello,

I ran that command line:  sudo stdbuf -oL libinput debug-events|grep switch 
but each time I've got an error : libinput error: event15-HTIX5288:00 0911:5288 Touchpad: kernel bug: clickpad advertising right button.

I don't know why I've got this message because the touchpad works ?

I'm using 5.0.0-25-generic kernel from Ubuntu and my system is based on Ubuntu 18.04.

Regards.

**Comment by alesguzik** [comment]
Most likely this error is just a warning that libinput prints to stderr (that's why you see it even though grep should filter out everything that doesn't contain "switch"), it shouldn't prevent the script from working.

**Comment by Tuxman2** [comment]
Hi Ales,

this problem is well know. See it: 

https://git.kernel.org/pub/scm/linux/kernel/git/jikos/hid.git/commit?id=807588ac92018bde88a1958f546438e840eb0158

https://bugzilla.kernel.org/show_bug.cgi?id=199821

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=807588ac92018bde88a1958f546438e840eb0158

But it seems to not be available in Ubuntu kernel. I tried with the 5.2.11 kernel (from kernel mainline ppa ubuntu) and I've got the same error message.
